language: python
python:
    - "2.6"
    - "2.7"
    - "3.4"
    - "3.5"
    - "nightly"
    - "pypy"
    - "pypy3"

install:
    - pip install flake8
    - pip install pytest pytest-cov
    - pip install -e .

script:
    - flake8
    - py.test --cov wait_for_port

